/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("java")

    // Hay que ponerle el lombok
    id("io.freefair.lombok") version "8.6"
    id("io.quarkus") version "3.11.1" 

}

group="com.distribuida"
version = "1.0.0-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

java{
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

val quarkusVersion = "3.11.1"

dependencies {
   implementation(enforcedPlatform("io.quarkus.platform:quarkus-bom:${quarkusVersion}"))
   implementation("io.quarkus:quarkus-arc") //motor de CDI
   implementation("io.quarkus:quarkus-resteasy-reactive")
   implementation("io.quarkus:quarkus-hibernate-orm-panache") //JPA - Hibernate + Repo

   implementation("org.postgresql:postgresql:42.7.3")
   implementation("io.quarkus:quarkus-jdbc-postgresql")


   implementation("io.quarkus:quarkus-resteasy-reactive-jackson") //JSON
implementation("io.quarkus:quarkus-rest-client-reactive") //cliente rest
implementation("io.quarkus:quarkus-rest-client-reactive-jackson") 
implementation("io.quarkus:quarkus-rest-client") //cliente rest
   
//    implementation("io.quarkus:quarkus-hibernate-orm") //JPA + Hibernate
//    implementation("com.h2database:h2:2.2.224")
}

